name: Sync Repositories

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Push to destination
        run: |
          git remote add destination "https://${{ secrets.SYNC_TOKEN }}@github.com/0xKoller/club.git"
          git push destination master:master --force